version: "3.8"

services:
  voucherdb:
    image: mysql:latest # Consider using a specific version (e.g., postgres:14)
    container_name: voucher-db
    # restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD} # Use environment variables for security
      - MYSQL_DATABASE=${DB_MST}
    ports:
      - ${DB_PORT_EXPOSE}:${DB_DEFAULTPORT}
    volumes:
      - voucherdb_data:/var/lib/mysql

  # service-voucher:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   restart: always
  #   container_name: service-voucher
  #   environment:
  #     - DB_CHARNTIME=${DB_CHARNTIME}
  #     - APP_PORT=5001
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_USER=${DB_USER}
  #     - DB_PASS=${DB_PASS}
  #     - DB_MST=${DB_MST}
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - voucherdb

volumes:
  voucherdb_data: